server:
  port: 8080
cors:
  originsPatterns: http://localhost:4200
spring:
  application:
    name: clientapi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/client_api_db?Timezone=true&serverTimezone=UTC
    username: ${USERNAME_DB}
    password: ${USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org:
        springframework:
          web: WARN

